#!c:\users\jaswi\onedrive\desktop\github_workspace\assignment-3-part-2\env\scripts\python.exe
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from htmlparser import standalone

standalone.main()
